config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root "friends#index"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    has_one_attached :featured_image
    has_rich_text :description
    validates :full_name, presence: true
    validates :email, presence: true
    validates :phone, presence: true
    validates :facebook, presence: true
    validates :description, presence: true
    validates :featured_image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.expect(friend: [ :full_name, :email, :phone, :facebook, :description, :featured_image ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group mb-3">
    <%= form.label :full_name %>
    <%= form.text_field :full_name, class:"form-control", placeholder:"Họ tên", required: true %>
  </div>

  <div class="field form-group mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email", required: true %>
  </div>

  <div class="field form-group mb-3">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control", placeholder:"SĐT", required: true %>
  </div>

  <div class="field form-group mb-3">
    <%= form.label :facebook %>
    <%= form.text_field :facebook, class:"form-control", placeholder:"Facebook", required: true %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description, required: true %>
  </div>

  <div>
    <%= form.label :featured_image, style: "display: block" %>
    <%= form.file_field :featured_image, accept: "image/*" %>
  </div>

  <br/>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>Họ Tên:</strong>
    <%= friend.full_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>SĐT:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Facebook:</strong>
    <%= friend.facebook %>
  </p>

</div>

app/views/friends/edit.html.erb
<% content_for :title, "Editing friend" %>

<h1>Trang chỉnh sửa</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Chi tiết", @friend, class:"btn btn-secondary" %> 
  <%= link_to "Quay lại", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/index.html.erb
<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Họ Tên</th>
        <th>Email</th>
        <th>SĐT</th>
        <th>Facebook</th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <tr>
          <td>
            <%= link_to friend.full_name, friend, class:"link-offset-2 link-underline link-underline-opacity-0 text-dark" %>
          </td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.facebook %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/friends/new.html.erb
<% content_for :title, "New friend" %>

<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Quay lại", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.full_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %>  | 
    <%= @friend.phone %>  |  
    <%= @friend.facebook %>
    <%= @friend.description %>
    <br>
    <%= image_tag @friend.featured_image, style: "width: 200px; height: 200px; object-fit: cover;", alt: @friend.full_name if @friend.featured_image.attached? %>
  </p>
</div>
<div style="display:flex; justify-content: space-between; width:200px;">
    <% if user_signed_in? %>
    <%= link_to 'Chỉnh sửa', edit_friend_path(@friend), class:"btn btn-secondary mr-1" %>
    <%= button_to "Xoá", @friend, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger delete-button mr-1" %>
    <% end %>
    <%= link_to 'Quay lại', friends_path, class:"btn btn-dark" %>
  </div>

app/views/home/_header.html.erb
<header>
  <div class="header-top">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 col-left">
        <div>Mở cửa: 8:30 - 22h00, thứ 2 - CN hàng tuần</div>
      </div>
      <div class="col-12 col-md-6 col-right">
        <div class="d-flex flex-end">
          <div class="item">
            <span>
            <i class="bi bi-person-fill fst-normal"></i>
            </span>
            <a href="#">Tài khoản</a>
            <% if user_signed_in? %>
            <div class="wrap-account">
              <%= link_to "Tài khoản", edit_user_registration_path, class: "d-block", data: { turbo: false } %>
              <%= button_to "Đăng xuất", destroy_user_session_path, method: :delete, class: "d-block btn-register", data: { turbo: false } %>								
            </div>
          <% else %>
            <div class="wrap-account">
              <%= link_to "Đăng nhập", new_user_session_path, class: "d-block", data: { turbo: false } %>
              <%= link_to "Đăng ký", new_user_registration_path, class: "d-block", data: { turbo: false } %>								
            </div>
          <% end %>
          </div>
          <div class="item"><span><i class="fas fa-map-marker-alt"></i></span><a href="">Hệ thống cửa hàng</a></div>
        </div>
      </div>
    </div>
  </div>
  </div>
</header>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <span data-turbo="false" class="navbar-brand mx-auto"><%= link_to "HOME", root_path, class:"navbar-brand" %></span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in? %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Add Friend", new_friend_path, class:"nav-link" %>
        </li>
      </ul>
    <% end %>
    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Họ Tên</th>
        <th>Email</th>
        <th>SĐT</th>
        <th>Facebook</th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <tr>
          <td>
            <%= link_to friend.full_name, friend, class:"link-offset-2 link-underline link-underline-opacity-0 text-dark" %>
          </td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.facebook %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Friends" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <%= render "home/header" %>
    <div class="container">
      <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>